// PDF Report Generation for GrantThrive ROI Calculator
// Using jsPDF library for client-side PDF generation

export function generateROIPDFReport(results, inputs, councilSize, features) {
  // This is a placeholder for PDF generation functionality
  // In a production environment, you would use jsPDF or similar library
  
  const reportData = {
    title: "GrantThrive ROI Analysis Report",
    generatedDate: new Date().toLocaleDateString('en-AU'),
    councilProfile: {
      size: councilSize.charAt(0).toUpperCase() + councilSize.slice(1),
      applications: inputs.applications,
      staffHours: inputs.currentStaffHours,
      staffRate: inputs.staffHourlyRate,
      techCosts: inputs.currentTechCosts,
      adminCosts: inputs.currentAdminCosts
    },
    financialResults: {
      roi: results.financial.roi,
      payback: results.financial.payback,
      annualSavings: results.summary.annualSavings,
      fiveYearValue: results.summary.fiveYearValue,
      totalSavings: results.financial.totalSavings
    },
    costBreakdown: {
      currentCosts: results.costs.current,
      grantThriveCosts: results.costs.grantThrive
    },
    benefits: results.benefits,
    features: {
      base: results.features.baseIncluded,
      addOns: results.features.addOns
    }
  };

  return reportData;
}

export function downloadROIReport(results, inputs, councilSize, features) {
  const reportData = generateROIPDFReport(results, inputs, councilSize, features);
  
  // Create a simple text-based report for now
  // In production, this would generate a proper PDF
  const reportText = `
GRANTTHRIVE ROI ANALYSIS REPORT
Generated: ${reportData.generatedDate}

COUNCIL PROFILE
===============
Size: ${reportData.councilProfile.size} Council
Annual Applications: ${reportData.councilProfile.applications}
Current Hours per Application: ${reportData.councilProfile.staffHours}
Staff Hourly Rate: $${reportData.councilProfile.staffRate}
Current Technology Costs: $${reportData.councilProfile.techCosts.toLocaleString()}
Current Administrative Costs: $${reportData.councilProfile.adminCosts.toLocaleString()}

FINANCIAL RESULTS
=================
ROI: ${reportData.financialResults.roi}%
Payback Period: ${reportData.financialResults.payback} months
Annual Savings: $${reportData.financialResults.annualSavings.toLocaleString()}
5-Year Value: $${reportData.financialResults.fiveYearValue.toLocaleString()}
Total Cost Savings: $${reportData.financialResults.totalSavings.toLocaleString()}

COST BREAKDOWN
==============
Current Annual Costs:
- Staff Time: $${reportData.costBreakdown.currentCosts.staffCosts.toLocaleString()}
- Technology: $${reportData.costBreakdown.currentCosts.techCosts.toLocaleString()}
- Administrative: $${reportData.costBreakdown.currentCosts.adminCosts.toLocaleString()}
- Total: $${reportData.costBreakdown.currentCosts.totalCurrentCosts.toLocaleString()}

GrantThrive Annual Costs:
- Base Platform: $${reportData.costBreakdown.grantThriveCosts.basePrice.toLocaleString()}
- Community Features: $${reportData.costBreakdown.grantThriveCosts.addOnCosts.toLocaleString()}
- Total: $${reportData.costBreakdown.grantThriveCosts.totalAnnualCost.toLocaleString()}

BENEFITS ANALYSIS
=================
Hours Saved per Application: ${reportData.benefits.hoursSavedPerApplication}
Total Annual Hours Saved: ${reportData.benefits.totalHoursSaved.toLocaleString()}
Staff Time Savings Value: $${reportData.benefits.staffTimeSavings.toLocaleString()}
Technology Savings: $${reportData.benefits.techSavings.toLocaleString()}
Administrative Savings: $${reportData.benefits.adminSavings.toLocaleString()}

INCLUDED FEATURES
=================
${reportData.features.base.map(feature => `✓ ${feature}`).join('\n')}

COMMUNITY ENGAGEMENT ADD-ONS
============================
Community Voting: ${reportData.features.addOns.communityVoting}
Grant Mapping: ${reportData.features.addOns.grantMapping}

CONCLUSION
==========
GrantThrive delivers exceptional value with a ${reportData.financialResults.roi}% ROI and payback period of just ${reportData.financialResults.payback} months. 
Your council will save $${reportData.financialResults.annualSavings.toLocaleString()} annually while gaining access to revolutionary community engagement features 
that no competitor offers.

Contact GrantThrive today to schedule your demonstration and begin your digital transformation journey.

---
This report was generated by the GrantThrive ROI Calculator
Visit: https://grantthrive.com.au
Email: info@grantthrive.com.au
Phone: 1300 GRANTS (1300 472 687)
  `;

  // Create and download the report as a text file
  const blob = new Blob([reportText], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `GrantThrive_ROI_Report_${reportData.generatedDate.replace(/\//g, '-')}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function formatReportForEmail(results, inputs, councilSize, features) {
  const reportData = generateROIPDFReport(results, inputs, councilSize, features);
  
  return {
    subject: `GrantThrive ROI Analysis - ${reportData.financialResults.roi}% ROI with ${reportData.financialResults.payback} month payback`,
    body: `
Dear Council Decision Maker,

Thank you for using the GrantThrive ROI Calculator. Based on your council's profile, here are your personalized results:

KEY FINANCIAL BENEFITS:
• ROI: ${reportData.financialResults.roi}%
• Payback Period: ${reportData.financialResults.payback} months
• Annual Savings: $${reportData.financialResults.annualSavings.toLocaleString()}
• 5-Year Value: $${reportData.financialResults.fiveYearValue.toLocaleString()}

YOUR COUNCIL PROFILE:
• Size: ${reportData.councilProfile.size} Council
• Annual Applications: ${reportData.councilProfile.applications}
• Current Processing Time: ${reportData.councilProfile.staffHours} hours per application
• GrantThrive Processing Time: 0.5 hours per application (87% time savings)

NEXT STEPS:
1. Schedule a personalized demonstration
2. See GrantThrive's community engagement features in action
3. Discuss implementation timeline and support
4. Begin your digital transformation journey

Ready to revolutionize your grant management? 
Contact us today: info@grantthrive.com.au | 1300 GRANTS

Best regards,
The GrantThrive Team
    `
  };
}

